version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
      examples:
        patterns:
          - next
          - react
          - react-dom
          - vite
          - '@vitejs/*'
          - '@iconify-json/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
